### ISSUE TITLE
Can't import in node Vue?

### ISSUE THREAD

**Issue by blkhwks19** [CrazyTim/spin-wheel#25]
I'm trying to install and import this into a node Vue project and I keep getting an error that the module cannot be resolved. 

My command to install: 
`npm install spin-wheel`

My code to import:
`import { Wheel } from "spin-wheel";`

Error I get:
`Module not found: Error: Can't resolve 'spin-wheel' in 'C:\Projects\Web\wheel-test\src'`

 I've checked package.json and it's definitely in there: `"spin-wheel": "^4.3.0",`. I'm getting the error before I've even begun to setup the config and initialize it. It can't even find the module. Is there a preferred way to import this that I'm missing?

**Comment by blkhwks19** [comment]
I was importing incorrectly. The correct way to import is: `import { Wheel } from "spin-wheel/src/wheel";`

**Comment by CrazyTim** [comment]
Hey @blkhwks19, thanks for raising this! 

I did notice a simular error when building for production in a Vue 3 app. It was because there was no entrypoints defined in `package.json`. This has been fixed in [v4.3.1](https://github.com/CrazyTim/spin-wheel/releases/tag/4.3.1) so hopefully it will make it easier to import and bundle now.
