### ISSUE TITLE
Add animated wheel overlay images

### ISSUE THREAD

**Issue by Amitnale007** [CrazyTim/spin-wheel#31]
Wanna add animated wheel overlay images..... I tried to add other overlay svg file but it is not rendering what's the issue?

**Comment by CrazyTim** [comment]
Hi @Amitnale007,

This library uses the Canvas API, and the spec says [only the first frame](https://html.spec.whatwg.org/multipage/canvas.html#image-sources-for-2d-rendering-contexts%3Acanvasimagesource-3) of SVG images should be drawn. It would be nice to be able to do this, but I don't think its supported by the tech, and I can't think of an easy way to add support for this.

As a workaround, and because you simply want to *overlay* an animated svg image, try adding the svg element to the DOM and then position it over the top of the wheel container using css (for example: `position: absolute`).
